/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../../../public/test_05.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/test_05.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BezierCurve.geometry} material={materials['Material.001']} rotation={[0, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/test_05.glb')
